"""
Django settings for omoide_teikibin_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


if os.getenv("APP_ENV", "dev") == "dev":
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_hc$^fumw86*^7w$mbk%31mi%yu+vb6!)tb2)cm!i@+rs(3e$r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

domain = [
    "127.0.0.1",
    "localhost",
    "app.omoide-teikibin.net",
    "omoide-teikibin.net",
    "omoide-teikibin-front.vercel.app"
]

url = [
    "https://omoide-teikibin-front.vercel.app",
    "https://app.omoide-teikibin.net",
    "http://localhost:3000"
]

ALLOWED_HOSTS = domain
CORS_ALLOWED_ORIGINS = url
CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_DOMAIN = ".omoide-teikibin.net"
CSRF_COOKIE_DOMAIN = ".omoide-teikibin.net"

CSRF_TRUSTED_ORIGINS = url

SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'corsheaders',
    
    "accounts",
    "post",
    "friend"
]

"""R2"""

USE_R2 = os.getenv("USE_R2", "0") == "1"

if USE_R2:
    INSTALLED_APPS += ["storages"]

    bucket = os.getenv("R2_BUCKET_NAME")
    endpoint = os.getenv("R2_ENDPOINT_URL")
    access_key = os.getenv("R2_ACCESS_KEY_ID")
    secret_key = os.getenv("R2_SECRET_ACCESS_KEY")
    domain = os.getenv("R2_PUBLIC_DOMAIN")

    if not all([bucket, endpoint, access_key, secret_key, domain]):
        raise RuntimeError("R2 env vars are missing (bucket/endpoint/keys/domain)")

    prefix = (os.getenv("R2_PREFIX", "") or "").strip("/")

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": bucket,
                "endpoint_url": endpoint,
                "access_key": access_key,
                "secret_key": secret_key,
                "region_name": "auto",
                "signature_version": "s3v4",
                "addressing_style": "path",
                "querystring_auth": False,
                "custom_domain": domain,
                "location": prefix,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    MEDIA_URL = f"https://{domain}/" + (f"{prefix}/" if prefix else "")
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
"""R2"""

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 削除ユーザーがリクエスト毎にログアウト実行
    "accounts.middleware.logout_if_deleted.LogoutIfDeletedMiddleware",
]

ROOT_URLCONF = 'omoide_teikibin_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                    BASE_DIR,"omoide_teikibin_project/templates",
                    BASE_DIR,"accounts/templates",
                    BASE_DIR,"friend/templates",
                    BASE_DIR,"post/templates"
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'omoide_teikibin_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.CustomUser"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"



# コンソールにメールを表示させる
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'