# Generated by Django 5.2 on 2025-11-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン'),
        ),
    ]
