# Generated by Django 5.2 on 2025-11-17 01:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.gen_image_path_customuser, verbose_name='アイコン'),
        ),
    ]
