# Generated by Django 5.2 on 2025-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.CharField(blank=True, null=True, verbose_name='自己紹介'),
        ),
    ]
