# Generated by Django 5.2 on 2025-11-10 05:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='グループID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='グループ名')),
                ('group_description', models.TextField(blank=True, null=True, verbose_name='グループ説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'グループ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ブログ投稿ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='著者')),
            ],
            options={
                'verbose_name': 'ブログ投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='通知ID')),
                ('message', models.CharField(max_length=255, verbose_name='メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='受取人')),
            ],
            options={
                'verbose_name': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='投稿ID')),
                ('post_content', models.TextField(verbose_name='投稿内容')),
                ('post_images', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='投稿画像')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='post.group')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.post', verbose_name='親投稿')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='投稿ユーザー')),
            ],
            options={
                'verbose_name': '投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='参加日時')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='退会日時')),
                ('role', models.BooleanField(default=False, verbose_name='役割')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='post.group', verbose_name='グループ')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
            options={
                'verbose_name': 'メンバー',
                'unique_together': {('username', 'group')},
            },
        ),
    ]
