# Generated by Django 5.2 on 2025-11-12 02:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='グループ名')),
                ('group_description', models.TextField(blank=True, null=True, verbose_name='グループ説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='投稿ID')),
                ('post_content', models.TextField(verbose_name='投稿内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('post_images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='投稿画像')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.group')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='親投稿')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(default=False, verbose_name='権限区分')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='参加日時')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='退会日時')),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終閲覧日時')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.group')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名')),
            ],
            options={
                'verbose_name': 'メンバー',
                'constraints': [models.UniqueConstraint(fields=('group', 'member'), name='group_unique_pair')],
            },
        ),
    ]
