# Generated by Django 5.2 on 2025-11-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='post_user',
        ),
    ]
