# Generated by Django 5.2 on 2025-11-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_username_post_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='グループ画像'),
        ),
    ]
