# Generated by Django 5.2 on 2025-11-17 07:07

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_group_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.gen_image_path_group, verbose_name='グループ画像'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='グループ名'),
        ),
    ]
