# Generated by Django 5.2 on 2026-01-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_group_group_image_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True, null=True, verbose_name='投稿内容'),
        ),
    ]
