# Generated by Django 5.2 on 2026-01-21 02:46

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.gen_image_path_post, verbose_name='投稿画像'),
        ),
    ]
