# Generated by Django 5.2 on 2025-11-06 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False, verbose_name='フレンド')),
                ('status', models.CharField(choices=[('A2B', 'A→B申請'), ('B2A', 'B→A申請'), ('ACPT', '承認')], default='A2B', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('friend_date', models.DateTimeField(blank=True, null=True, verbose_name='フレンド成立日')),
                ('username_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_as_a', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーA')),
                ('username_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_as_b', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーB')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='メッセージ画像')),
                ('message_text', models.TextField(blank=True, null=True, verbose_name='メッセージ内容')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('sender_a', models.BooleanField(default=True, verbose_name='送信者がAか')),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend.friendship', verbose_name='フレンド')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('username_a', models.F('username_b')), _negated=True), name='friend_a_noteq_b'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('username_a__lt', models.F('username_b'))), name='friend_a_less_than_username_b'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('username_a', 'username_b'), name='friend_unique_pair'),
        ),
    ]
