# Generated by Django 5.2 on 2025-11-10 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'フレンド'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'メッセージ'},
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='friend_a_less_than_username_b',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='friend_unique_pair',
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('username_a__lt', models.F('username_b'))), name='combinations_already_exist'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('username_a', 'username_b'), name='friend_unique'),
        ),
    ]
