# Generated by Django 5.2 on 2025-11-11 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friendship_options_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='friend_a_noteq_b',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='combinations_already_exist',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='friend_unique',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='username_a',
            new_name='user_a',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='username_b',
            new_name='user_b',
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user_a', models.F('user_b')), _negated=True), name='friend_a_noteq_b'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user_a__lt', models.F('user_b'))), name='combinations_already_exist'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='friend_unique'),
        ),
    ]
