# Generated by Django 5.2 on 2025-11-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_alter_message_sender_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_a',
            new_name='sender',
        ),
    ]
