# Generated by Django 5.2 on 2025-11-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_rename_sender_a_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='フレンド解消日'),
        ),
    ]
