# Generated by Django 5.2 on 2025-11-12 02:00

import friend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_friendship_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to=friend.models.gen_image_path_message, verbose_name='メッセージ画像'),
        ),
    ]
