# Generated by Django 5.2 on 2026-01-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0007_alter_message_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='申請日'),
        ),
    ]
