# Generated by Django 5.2 on 2026-02-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0008_friendship_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='フレンド成立日'),
        ),
    ]
