# Generated by Django 5.2 on 2026-02-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0009_alter_friendship_friend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='フレンド成立日'),
        ),
    ]
