# Generated by Django 5.2 on 2026-02-05 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0010_alter_friendship_friend_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='combinations_already_exist',
        ),
    ]
