# Generated by Django 5.2 on 2026-02-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0012_friendship_combinations_already_exist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='combinations_already_exist',
        ),
    ]
