# Generated by Django 5.2 on 2026-01-21 02:46

import django.db.models.deletion
import notify.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_alter_post_post_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notify_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100, verbose_name='メッセージ内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to=notify.models.gen_image_path_message, verbose_name='メッセージ画像')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('send_at', models.DateTimeField(auto_now_add=True, verbose_name='通知日時')),
                ('status', models.CharField(choices=[('post', 'post'), ('friend', 'friend'), ('message', 'message'), ('else', 'else')], db_index=True, default='else', max_length=10, verbose_name='通知状態')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to=settings.AUTH_USER_MODEL, verbose_name='送信者')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
    ]
