# Generated by Django 5.2 on 2026-01-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
    ]
