# Generated by Django 5.2 on 2026-01-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_remove_notification_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='send_at',
            new_name='created_at',
        ),
    ]
